
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'behaviorADD AND COMMA COMPARISON COR DOT EQUAL EXIST LENGTH LPAREN MNODE NODE NOT NUMBER OR RPAREN STARbehavior : match_op COMMA path_exp\n                 | LPAREN behavior RPARENmatch_op : EQUAL\n                 | EXIST COMPARISON NUMBERpath_exp : LPAREN _path_exp RPAREN\n                 | _path_exp\n                 | LPAREN _path_exp COMMA length_filter RPAREN\n    length_filter : LPAREN _length_filter RPAREN\n                      | length_filter_length_filter : COMPARISON NUMBER\n                       | COMPARISON LENGTH\n                       | COMPARISON LENGTH ADD NUMBER_path_exp : _path_exp term\n                 | term term : NODE\n             | MNODE\n             | STAR\n             | DOT\n             | COR\n             | AND\n             | NOT\n             | OR'
    
_lr_action_items = {'LPAREN':([0,3,6,26,],[3,3,10,27,]),'EQUAL':([0,3,],[4,4,]),'EXIST':([0,3,],[5,5,]),'$end':([1,9,11,12,13,14,15,16,17,18,19,20,21,24,25,31,],[0,-1,-6,-14,-15,-16,-17,-18,-19,-20,-21,-22,-2,-13,-5,-7,]),'COMMA':([2,4,12,13,14,15,16,17,18,19,20,22,23,24,],[6,-3,-14,-15,-16,-17,-18,-19,-20,-21,-22,-4,26,-13,]),'COMPARISON':([5,27,],[8,30,]),'NODE':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[13,13,13,-14,-15,-16,-17,-18,-19,-20,-21,-22,13,-13,]),'MNODE':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[14,14,14,-14,-15,-16,-17,-18,-19,-20,-21,-22,14,-13,]),'STAR':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[15,15,15,-14,-15,-16,-17,-18,-19,-20,-21,-22,15,-13,]),'DOT':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[16,16,16,-14,-15,-16,-17,-18,-19,-20,-21,-22,16,-13,]),'COR':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[17,17,17,-14,-15,-16,-17,-18,-19,-20,-21,-22,17,-13,]),'AND':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[18,18,18,-14,-15,-16,-17,-18,-19,-20,-21,-22,18,-13,]),'NOT':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[19,19,19,-14,-15,-16,-17,-18,-19,-20,-21,-22,19,-13,]),'OR':([6,10,11,12,13,14,15,16,17,18,19,20,23,24,],[20,20,20,-14,-15,-16,-17,-18,-19,-20,-21,-22,20,-13,]),'RPAREN':([7,9,11,12,13,14,15,16,17,18,19,20,21,23,24,25,28,29,31,32,33,34,36,],[21,-1,-6,-14,-15,-16,-17,-18,-19,-20,-21,-22,-2,25,-13,-5,31,32,-7,-8,-10,-11,-12,]),'NUMBER':([8,30,35,],[22,33,36,]),'LENGTH':([30,],[34,]),'ADD':([34,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'behavior':([0,3,],[1,7,]),'match_op':([0,3,],[2,2,]),'path_exp':([6,],[9,]),'_path_exp':([6,10,],[11,23,]),'term':([6,10,11,23,],[12,12,24,24,]),'length_filter':([26,],[28,]),'_length_filter':([27,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> behavior","S'",1,None,None,None),
  ('behavior -> match_op COMMA path_exp','behavior',3,'p_behavior','parser.py',6),
  ('behavior -> LPAREN behavior RPAREN','behavior',3,'p_behavior','parser.py',7),
  ('match_op -> EQUAL','match_op',1,'p_match_op_equal','parser.py',18),
  ('match_op -> EXIST COMPARISON NUMBER','match_op',3,'p_match_op_equal','parser.py',19),
  ('path_exp -> LPAREN _path_exp RPAREN','path_exp',3,'p_path_exp','parser.py',27),
  ('path_exp -> _path_exp','path_exp',1,'p_path_exp','parser.py',28),
  ('path_exp -> LPAREN _path_exp COMMA length_filter RPAREN','path_exp',5,'p_path_exp','parser.py',29),
  ('length_filter -> LPAREN _length_filter RPAREN','length_filter',3,'p_length_filter','parser.py',47),
  ('length_filter -> length_filter','length_filter',1,'p_length_filter','parser.py',48),
  ('_length_filter -> COMPARISON NUMBER','_length_filter',2,'p__length_filter','parser.py',54),
  ('_length_filter -> COMPARISON LENGTH','_length_filter',2,'p__length_filter','parser.py',55),
  ('_length_filter -> COMPARISON LENGTH ADD NUMBER','_length_filter',4,'p__length_filter','parser.py',56),
  ('_path_exp -> _path_exp term','_path_exp',2,'p__path_exp','parser.py',61),
  ('_path_exp -> term','_path_exp',1,'p__path_exp','parser.py',62),
  ('term -> NODE','term',1,'p_term','parser.py',70),
  ('term -> MNODE','term',1,'p_term','parser.py',71),
  ('term -> STAR','term',1,'p_term','parser.py',72),
  ('term -> DOT','term',1,'p_term','parser.py',73),
  ('term -> COR','term',1,'p_term','parser.py',74),
  ('term -> AND','term',1,'p_term','parser.py',75),
  ('term -> NOT','term',1,'p_term','parser.py',76),
  ('term -> OR','term',1,'p_term','parser.py',77),
]
